name = "status"
main = "src/worker.js"
compatibility_date = "2024-12-05"

[[kv_namespaces]]
binding = "STATUS_KV"
id = "3649b85964d649ea9dceda130f30b836"
preview_id = "3649b85964d649ea9dceda130f30b836"

[vars]
# AUTH_TOKEN is a secret – set it with: wrangler secret put AUTH_TOKEN

# Uncomment to set a custom page title:
# PAGE_TITLE = "My Status"
